language: python
python:
  - "3.7"
install:
  - pip --quiet install ansible
before_script:
  - ansible-playbook --version
script:
  - ansible-playbook --syntax-check google-assistant-on-pi.yml
branches:
  only: [master]
