---

- name: Install Python virtual environment dependencies
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python3-dev
    - python3-venv
    - python-setuptools # Required for Ansible only

- name: Create a Python virtual environment
  shell: python3 -m venv env # Ansible pip module can't handle venv well

- name: Configure a new Python virtual environment
  shell: env/bin/python -m pip install --upgrade pip setuptools wheel # Ansible pip module can't handle venv well

- name: Install Google Assistant SDK system dependencies
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - portaudio19-dev
    - libffi-dev
    - libssl-dev
    - libmpg123-dev

- name: Install Google Assistant SDK and the examples
  pip:
    name:
    - google-assistant-library
    - google-assistant-sdk[samples]
    virtualenv: env
    virtualenv_python: python3
    state: latest # corresponds '--upgrade'

- name: Find GCP key file
  find:
    paths: .
    patterns: 'client_secret_*.json'
  register: gcp_key_file

- name: Missing GCP key file
  debug:
    msg: "GCP key file ~/.client_secret_*.json is missing"
  when: not gcp_key_file.files

- name: Output command for OAuth
  debug:
    msg: "Please run on the Pi:\
    . env/bin/activate && \
    google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
      --scope https://www.googleapis.com/auth/gcm \
      --save --headless --client-secrets {{ gcp_key_file.files[0]['path'] }}"
  when: gcp_key_file.files and gcp_key_file.files[0]['path']
